// ...existing code...
public class DataflowRunnerService {
    // ...existing code...
    private LoadConfig config;
    // ...existing code...

    public void startLoadOperation() {
        if (config == null) {
            throw new IllegalStateException("LoadConfig 'config' is not initialized in DataflowRunnerService.");
        }
        // ...existing code...
        config.getSource();
        // ...existing code...
    }
    // ...existing code...
}

